name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Login a Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Crear imagen
        run: docker build -t fernandaballesteros/music-api-411:latest .

      - name: Publicar imagen
        run: docker push fernandaballesteros/music-api-411:latest
